apiVersion: v1
kind: ConfigMap
metadata:
  name: hello-content-pattern2
  namespace: default
data:
  version: "v1-edge02"
  index.html: |
    <html><body style="font-family:sans-serif;text-align:center;padding-top:80px;background:#fff0f6">
      <h1>Hello from Fleet</h1>
      <h2>deploy version: v1</h2>
      <p>pattern2: I am <b>edge02</b> (per-cluster customized)</p>
    </body></html>
