apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: monitor
  namespace: edge-apps
spec:
  selector:
    matchLabels: { app: monitor }
  template:
    metadata:
      labels: { app: monitor }
    spec:
      containers:
        - name: monitor
          image: busybox:1.36
          imagePullPolicy: IfNotPresent
          command: ["/bin/sh","-c","while true; do echo monitoring; sleep 60; done"]
